export const SUBMIT_COMMENT = 'POSTCONTENTPAGE/SUBMIT_COMMENT'
export const SUBMIT_COMMENT_SUCCESS = 'POSTCONTENTPAGE/SUBMIT_COMMENT_SUCCESS'
export const SUBMIT_COMMENT_FAILED = 'POSTCONTENTPAGE/SUBMIT_COMMENT_FAILED'